# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Enumerate in-window (response, covariate) pairs within subject
#'
#' @keywords internal
#' @noRd
async_pairs_cpp <- function(y_sub, y_time, x_time, lo, hi, h, supp_lo, supp_hi) {
    .Call(`_skmle_async_pairs_cpp`, y_sub, y_time, x_time, lo, hi, h, supp_lo, supp_hi)
}

#' Collapse weighted pairs onto covariate rows (time-invariant coefficients)
#'
#' @keywords internal
#' @noRd
async_pair_accum_cpp <- function(pj, pk, w, yv, n_x) {
    .Call(`_skmle_async_pair_accum_cpp`, pj, pk, w, yv, n_x)
}

#' Build the collapsed weights at one target time (time-dependent coefficients)
#'
#' @keywords internal
#' @noRd
async_td_accum_cpp <- function(y_sub, wy, yv, x_sub, vx, n) {
    .Call(`_skmle_async_td_accum_cpp`, y_sub, wy, yv, x_sub, vx, n)
}

#' Solve the collapsed kernel-weighted estimating equation
#'
#' @keywords internal
#' @noRd
async_solve_cpp <- function(Xs, x_sub, omega, cc, n, link, maxit, tol, start) {
    .Call(`_skmle_async_solve_cpp`, Xs, x_sub, omega, cc, n, link, maxit, tol, start)
}

kee_cox_estequ <- function(beta, covariates, X, obs_times, delta, kerval, h, n_subj, one_sided = TRUE) {
    .Call(`_skmle_kee_cox_estequ`, beta, covariates, X, obs_times, delta, kerval, h, n_subj, one_sided)
}

kee_cox_var <- function(beta, covariates, X, obs_times, delta, kerval, h, one_sided, id, n_subj) {
    .Call(`_skmle_kee_cox_var`, beta, covariates, X, obs_times, delta, kerval, h, one_sided, id, n_subj)
}

kee_additive_est <- function(covariates, X, obs_times, delta, kerval, h, tau, one_sided, id, lq_x, lq_w, n_subj) {
    .Call(`_skmle_kee_additive_est`, covariates, X, obs_times, delta, kerval, h, tau, one_sided, id, lq_x, lq_w, n_subj)
}

skmle_cpp_fit <- function(n, p, gammap, s, h, tau, covariates, bsmat, X, obs_times, delta, kerval, lq_x, lq_w, bsmat_tt_all, kerval_tt_all, ineqmat, maxeval, xtol_rel) {
    .Call(`_skmle_skmle_cpp_fit`, n, p, gammap, s, h, tau, covariates, bsmat, X, obs_times, delta, kerval, lq_x, lq_w, bsmat_tt_all, kerval_tt_all, ineqmat, maxeval, xtol_rel)
}

calc_A <- function(beta, gamma, s, h, one_sided, covariates, bsmat, X, obs_times, delta, kerval, bsmat_XX, n_subj) {
    .Call(`_skmle_calc_A`, beta, gamma, s, h, one_sided, covariates, bsmat, X, obs_times, delta, kerval, bsmat_XX, n_subj)
}

calc_B <- function(beta, gamma, s, h, tau, one_sided, covariates, bsmat, X, obs_times, delta, kerval, id, bsmat_XX, lq_x, lq_w, bsmat_tt_all, kerval_tt_all, n_subj) {
    .Call(`_skmle_calc_B`, beta, gamma, s, h, tau, one_sided, covariates, bsmat, X, obs_times, delta, kerval, id, bsmat_XX, lq_x, lq_w, bsmat_tt_all, kerval_tt_all, n_subj)
}

skmle_eval_nll_cpp <- function(n, p, gammap, s, h, tau, beta, gamma, covariates, bsmat, X, obs_times, delta, kerval, lq_x, lq_w, bsmat_tt_all, kerval_tt_all) {
    .Call(`_skmle_skmle_eval_nll_cpp`, n, p, gammap, s, h, tau, beta, gamma, covariates, bsmat, X, obs_times, delta, kerval, lq_x, lq_w, bsmat_tt_all, kerval_tt_all)
}

skmle_cv_cpp <- function(n, p, gammap, s, tau, h_grid, K, fold_id, id_vec, covariates, bsmat, X, obs_times, delta, lq_x, lq_w, bsmat_tt_all, maxeval, xtol_rel, quiet, one_sided) {
    .Call(`_skmle_skmle_cv_cpp`, n, p, gammap, s, tau, h_grid, K, fold_id, id_vec, covariates, bsmat, X, obs_times, delta, lq_x, lq_w, bsmat_tt_all, maxeval, xtol_rel, quiet, one_sided)
}

