# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kee_cox_estequ <- function(beta, covariates, X, obs_times, delta, kerval, h, n_subj) {
    .Call(`_skmle_kee_cox_estequ`, beta, covariates, X, obs_times, delta, kerval, h, n_subj)
}

kee_cox_var <- function(beta, covariates, X, obs_times, delta, kerval, h, id, n_subj) {
    .Call(`_skmle_kee_cox_var`, beta, covariates, X, obs_times, delta, kerval, h, id, n_subj)
}

kee_additive_est <- function(covariates, X, obs_times, delta, kerval, h, id, lq_x, lq_w, n_subj) {
    .Call(`_skmle_kee_additive_est`, covariates, X, obs_times, delta, kerval, h, id, lq_x, lq_w, n_subj)
}

skmle_cpp_fit <- function(n, p, gammap, s, h, covariates, bsmat, X, obs_times, delta, kerval, lq_x, lq_w, bsmat_tt_all, kerval_tt_all, ineqmat, maxeval, xtol_rel) {
    .Call(`_skmle_skmle_cpp_fit`, n, p, gammap, s, h, covariates, bsmat, X, obs_times, delta, kerval, lq_x, lq_w, bsmat_tt_all, kerval_tt_all, ineqmat, maxeval, xtol_rel)
}

calc_A <- function(beta, gamma, s, h, covariates, bsmat, X, obs_times, delta, kerval, bsmat_XX, n_subj) {
    .Call(`_skmle_calc_A`, beta, gamma, s, h, covariates, bsmat, X, obs_times, delta, kerval, bsmat_XX, n_subj)
}

calc_B <- function(beta, gamma, s, h, covariates, bsmat, X, obs_times, delta, kerval, id, bsmat_XX, lq_x, lq_w, bsmat_tt_all, kerval_tt_all, n_subj) {
    .Call(`_skmle_calc_B`, beta, gamma, s, h, covariates, bsmat, X, obs_times, delta, kerval, id, bsmat_XX, lq_x, lq_w, bsmat_tt_all, kerval_tt_all, n_subj)
}

