#' Generate Non-Homogeneous Poisson Process
#'
#' @description Generates event times from a Non-Homogeneous Poisson Process (NHPP)
#' with a specified intensity function. Used internally for simulating
#' observation times.
#'
#' @param lambdat A function specifying the intensity rate at time `t`.
#' @param censor The maximum follow-up or censoring time. Event times are generated up to this point.
#' @param lambda.bar An upper bound for the intensity function `lambdat` over the interval `[0, censor]`.
#' Needs to be strictly greater than or equal to `max(lambdat(t))` for valid generation.
#'
#' @return A numeric vector of sorted generated event times, or an empty vector if no events occurred.
#'
#' @importFrom stats rpois runif
#' @noRd
NonHPP_gen <- function(lambdat, censor, lambda.bar) {
    nn <- 0
    while (nn <= 0) {
        nn <- rpois(1, censor * lambda.bar)
        if (nn > 0) {
            tt <- sort(runif(nn, min = 0, max = censor))

            ind <- (sapply(tt, lambdat) / lambda.bar) > runif(nn)
            tt <- tt[ind]
        } else {
            tt <- numeric(0)
        }
        nn <- length(tt)
    }

    tt
}

#' Simulate Sparse Longitudinal Survival Data
#'
#' @description
#' Simulate right-censored survival data with sparsely and intermittently observed
#' longitudinal covariates under a transformed hazards model.
#'
#' @param n Number of subjects to simulate.
#' @param mu Function giving the intensity of the observation-time process for the
#'   longitudinal covariates.
#' @param mu_bar Numeric upper bound for `mu` on the follow-up interval.
#' @param alpha Function giving the baseline component of the transformed hazards model.
#' @param beta Numeric vector of true regression coefficients. The current simulator
#'   supports exactly two covariates, so `length(beta)` must equal `2`.
#' @param s Box-Cox transformation parameter. Use `s = 0` for a proportional hazards
#'   model and `s = 1` for an additive hazards model.
#' @param cen Positive censoring parameter controlling the follow-up window.
#' @param nstep Number of grid intervals used to generate the latent piecewise-constant
#'   time-varying covariate process.
#'
#' @details
#' The simulated data are returned in long format, with one row per subject-visit pair.
#' Each row contains the observed event or censoring time, the event indicator, the
#' observation time for the longitudinal covariate, and the covariate values observed
#' at that visit.
#'
#' The first covariate is generated as a latent step function over time. The second
#' covariate is a binary subject-level indicator. Event times are generated by numerically
#' inverting the cumulative transformed hazard, and observation times are generated from a
#' non-homogeneous Poisson process.
#'
#' @return
#' A tibble in long format with columns:
#'
#' * `id`: subject identifier.
#' * `X`: observed event or censoring time.
#' * `delta`: event indicator.
#' * `covariates`: a two-column matrix of observed covariates at `obs_times`.
#' * `obs_times`: longitudinal observation time.
#' * `censoring`: subject-specific censoring time.
#'
#' @examples
#' set.seed(123)
#' sim_data <- sim_skmle_data(
#'   n = 50,
#'   mu = function(tt) 8 * (0.75 + (0.5 - tt)^2),
#'   mu_bar = 8,
#'   alpha = function(tt) 0.5 * 0.75 + 0.75 * (tt * (1 - sin(2 * pi * (tt - 0.25)))),
#'   beta = c(1, -0.5),
#'   s = 0,
#'   cen = 0.7
#' )
#'
#' head(sim_data)
#' table(sim_data$delta)
#'
#' # The `covariates` column is a matrix; use it directly in model formulas
#' # or split it into explicit columns if preferred.
#' sim_data$Z1 <- sim_data$covariates[, 1]
#' sim_data$Z2 <- sim_data$covariates[, 2]
#' head(sim_data[, c("id", "X", "delta", "obs_times", "Z1", "Z2")])
#'
#' @importFrom stats pnorm runif stepfun
#' @importFrom MASS mvrnorm
#' @importFrom nleqslv nleqslv
#' @importFrom gaussquad legendre.quadrature legendre.quadrature.rules
#' @importFrom tibble tibble
#' @importFrom dplyr bind_rows
#' @export
sim_skmle_data <- function(n,
                           mu,
                           mu_bar,
                           alpha,
                           beta,
                           s,
                           cen,
                           nstep = 20) {
    ## input validation -------------------------------------------------------
    if (!is.numeric(n) || length(n) != 1 || n <= 0) {
        stop("'n' must be a positive integer")
    }
    if (!is.function(mu) || !is.function(alpha)) {
        stop("'mu' and 'alpha' must be functions of time")
    }
    if (!is.numeric(mu_bar) || length(mu_bar) != 1 || mu_bar <= 0) {
        stop("'mu_bar' must be a positive numeric value")
    }
    if (!is.numeric(beta) || length(beta) < 1) {
        stop("'beta' must be a numeric vector of length at least 1")
    }
    if (length(beta) != 2L) {
        stop("This simulation currently only supports two covariates (length(beta) == 2)")
    }
    if (!is.numeric(s) || length(s) != 1) {
        stop("'s' must be a numeric scalar")
    }
    if (!is.numeric(cen) || length(cen) != 1 || cen <= 0) {
        stop("'cen' must be a positive numeric value")
    }
    if (!is.numeric(nstep) || length(nstep) != 1 || nstep <= 0) {
        stop("'nstep' must be a positive integer")
    }

    # internal helper --------------------------------------------------------
    sim_single_subject <- function() {
        # 1. Generate censoring times (uniform over [cen,1] but not exceeding 1)
        cen_i <- runif(1, cen, 1.5)
        cen_i <- min(cen_i, 1)

        # 2. Generate Z(t) and h(t) as a step function
        Sigmat_z <- exp(-abs(outer(1:nstep, 1:nstep, "-")) / nstep)

        # Generate the first covariate (time-varying step function)
        z <- 2 * (pnorm(c(MASS::mvrnorm(1, rep(0, nstep), Sigmat_z))) - 0.5)
        left_time_points <- (0:(nstep - 1)) / nstep
        z_fun <- stepfun(left_time_points, c(0, z))

        # Generate the second covariate as a binary indicator
        z_cons_raw <- as.numeric((mean(z) + rnorm(1, 0, 1)) > 0)

        # The aggregated linear predictor part (used for survival time)
        h_fun <- function(x) {
            beta[1] * z_fun(x) + beta[2] * z_cons_raw
        }

        # 3. Generate failure time based on transformation parameter 's'
        if (s == 0) {
            lam_fun <- function(tt) exp(alpha(tt) + h_fun(tt))
        } else {
            lam_fun <- function(tt) (s * (alpha(tt) + h_fun(tt)) + 1)^(1 / s)
        }

        u <- runif(1)
        lqrule64 <- gaussquad::legendre.quadrature.rules(64)[[64]]

        # Solve for failure time using nleqslv and Legendre-Gauss Quadrature
        fail_time <- nleqslv::nleqslv(cen_i / 2, function(ttt) {
            gaussquad::legendre.quadrature(lam_fun, lower = 0, upper = ttt, lqrule64) + log(u)
        })$x

        X <- min(fail_time, cen_i)

        # 4. Generate R_ik (Observation times) via NHPP
        obs_times <- NonHPP_gen(mu, cen_i, mu_bar)
        if (length(obs_times) == 0) obs_times <- cen_i

        # Combine covariates evaluated at observation times
        covariates_obscov <- cbind(
            z_fun(obs_times),
            rep(z_cons_raw, length(obs_times))
        )
        colnames(covariates_obscov) <- paste0("cov", seq_len(ncol(covariates_obscov)))

        # Return results for the subject
        tibble::tibble(
            X = X,
            delta = fail_time < cen_i,
            covariates = covariates_obscov,
            obs_times = obs_times,
            censoring = cen_i
        )
    }

    # Simulate for 'n' subjects and bind rows
    res_list <- replicate(n, sim_single_subject(), simplify = FALSE)
    sim_data <- dplyr::bind_rows(res_list, .id = "id")

    return(sim_data)
}


#' Simulate asynchronous longitudinal data
#'
#' @description
#' Draw a sparse longitudinal response and a sparse longitudinal covariate whose
#' observation times are **independent**, so the two are never seen together.
#' This is the design of Cao, Zeng and Fine (2015), Section 4: response times and
#' covariate times are independent Poisson streams on \eqn{(0, 1)}, the covariate
#' is a mean-zero Gaussian process, and the error is a second, independent
#' Gaussian process.
#'
#' @details
#' The default covariate covariance \eqn{\exp(-|s - t|)} is the Ornstein-
#' Uhlenbeck covariance. Its diagonal has a kink, so it is only one-sided
#' differentiable, which is exactly the case Cao, Zeng and Fine's Section 6
#' leaves open. Supply a smooth
#' `x_cov`, for instance `function(s, t) exp(-(s - t)^2)`, to generate data
#' inside their stated assumptions instead.
#'
#' `beta` may be a numeric vector, giving time-invariant coefficients suitable
#' for [kee_async()], or a function of time returning one row per supplied time,
#' giving a coefficient curve suitable for [kee_async_td()]. In both cases the
#' first element is the intercept and the remaining `p` elements multiply the `p`
#' covariate coordinates.
#'
#' @param n Number of subjects.
#' @param beta Either a numeric vector `c(intercept, slopes)` or a function of a
#'   numeric time vector returning a matrix with `length(beta(t))` columns and
#'   one row per time.
#' @param lambda_y,lambda_x Poisson rates for the response and covariate
#'   observation streams on `(0, 1)`. Each subject is forced to have at least one
#'   observation of each.
#' @param link One of `"identity"`, `"log"` or `"logistic"`, matching
#'   [kee_async()]. Under `"logistic"` the response is Bernoulli and no error
#'   process is added; under `"log"` the response is Poisson.
#' @param x_cov,e_cov Covariance functions of two times, vectorised, for the
#'   covariate and error processes.
#'
#' @return A list with two data frames on different time grids:
#' \describe{
#'   \item{y}{`id`, `time`, `y` -- one row per response occasion.}
#'   \item{x}{`id`, `time`, `x` -- one row per covariate occasion, `x` being a
#'     matrix column with `p` columns.}
#' }
#'
#' @references
#' Cao, H., Zeng, D. and Fine, J. P. (2015). Regression analysis of sparse
#' asynchronous longitudinal data. \emph{Journal of the Royal Statistical
#' Society, Series B} 77, 755-776.
#'
#' @examples
#' set.seed(1)
#' d <- sim_async_data(n = 50)
#' str(d)
#'
#' # A coefficient curve, for kee_async_td().
#' d2 <- sim_async_data(n = 50, beta = function(tt) cbind(0.5, 1 + tt))
#' @importFrom stats rpois runif rnorm rbinom
#' @export
sim_async_data <- function(n, beta = c(0.5, 1.5), lambda_y = 5, lambda_x = 5,
                           link = c("identity", "log", "logistic"),
                           x_cov = function(s, t) exp(-abs(s - t)),
                           e_cov = function(s, t) 2^(-abs(s - t))) {
    link <- match.arg(link)
    if (!is.numeric(n) || length(n) != 1L || is.na(n) || n < 1) {
        stop("'n' must be a single positive number")
    }
    n <- as.integer(n)
    if (!is.function(beta) && !is.numeric(beta)) {
        stop("'beta' must be a numeric vector or a function of time")
    }

    # Coefficient dimension: probe the curve once if beta is a function.
    bdim <- if (is.function(beta)) ncol(as.matrix(beta(0.5))) else length(beta)
    if (is.null(bdim) || bdim < 2L) {
        stop("'beta' must supply an intercept and at least one slope")
    }
    p <- bdim - 1L

    # Draw a mean-zero Gaussian vector with the given covariance.  A tiny ridge
    # keeps the Cholesky alive when two observation times coincide.
    rgp <- function(tt, cov_fun) {
        K <- outer(tt, tt, cov_fun)
        as.numeric(t(chol(K + diag(1e-8, length(tt)))) %*% rnorm(length(tt)))
    }

    yl <- xl <- vector("list", n)
    for (i in seq_len(n)) {
        nT <- max(1L, rpois(1L, lambda_y))
        nS <- max(1L, rpois(1L, lambda_x))
        Tt <- sort(runif(nT))
        Ss <- sort(runif(nS))
        at <- c(Tt, Ss)

        # One draw per coordinate, over the pooled grid, so that X at a response
        # time and X at a covariate time come from the same realised path.
        Xa <- vapply(seq_len(p), function(j) rgp(at, x_cov), numeric(length(at)))
        Xt <- Xa[seq_len(nT), , drop = FALSE]
        Xs <- Xa[nT + seq_len(nS), , drop = FALSE]
        colnames(Xs) <- if (p == 1L) "x" else paste0("x", seq_len(p))

        bt <- if (is.function(beta)) {
            matrix(as.numeric(as.matrix(beta(Tt))), nT, bdim)
        } else {
            matrix(beta, nT, bdim, byrow = TRUE)
        }
        eta <- bt[, 1L] + rowSums(bt[, -1L, drop = FALSE] * Xt)

        yv <- switch(link,
            identity = eta + rgp(Tt, e_cov),
            log = rpois(nT, exp(eta)),
            logistic = rbinom(nT, 1L, 1 / (1 + exp(-eta)))
        )

        yl[[i]] <- data.frame(id = i, time = Tt, y = as.numeric(yv))
        xi <- data.frame(id = rep(i, nS), time = Ss)
        xi$x <- Xs
        xl[[i]] <- xi
    }

    y <- do.call(rbind, yl)
    x <- do.call(rbind, xl)
    rownames(y) <- rownames(x) <- NULL
    list(y = y, x = x)
}
